version: "3"
services:
        nginxproxy:
                image: nginx
                ports:
                - "80:80"
                volumes:
                - "/home/nawak/nginx.conf:/etc/nginx/nginx.conf"
                networks:
                        webnet:
                                aliases:
                                - nginxproxy

networks:
  webnet:

